const data = {
  products: [
    {
      name: 'TRAVEL BAG',
      slug: 'TRAVEL-BAG',
      category: 'Model-Y',
      image: '/images/tesla1.jpg',
      price: 70,
      brand: 'Tesla',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Tesla accessories',
    },
    {
      name: 'RUBBER MATS',
      slug: 'RUBBER MATS',
      category: 'Model-Y',
      image: '/images/tesla2.jpg',
      price: 80,
      brand: 'Tesla',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Tesla accessories',
    },
    {
      name: 'TESLA RING',
      slug: 'TESLA-RING',
      category: 'Model-Y',
      image: '/images/tesla3.jpg',
      price: 90,
      brand: 'Tesla',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Tesla accessories',
    },
    {
      name: 'CUP HOLDER',
      slug: 'CUP-HOLDER',
      category: 'Model-Y',
      image: '/images/tesla4.jpg',
      price: 90,
      brand: 'Tesla',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Tesla accessories',
    },
    {
      name: 'SCREEN',
      slug: 'SCREEN',
      category: 'Model-Y',
      image: '/images/tesla5.jpg',
      price: 95,
      brand: 'Tesla',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Tesla accessories',
    },
    {
      name: 'ARMREST',
      slug: 'ARMREST',
      category: 'Model-Y',
      image: '/images/tesla6.jpg',
      price: 75,
      brand: 'Tesla',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Tesla accessories',
    },
  ],
};

export default data;
